trigger:
  branches:
    include:
      - main
  paths:
    include: 
      - /dependency/dependency-ex1.yml
pool:
  vmImage: ubuntu-latest

stages:
- stage: A
  jobs:
   - job: Job1
     displayName: Stage_1
     continueOnError: true
     workspace:
      clean: outputs
     steps:
     - script: echo step 1 
       displayName: step 1
     - script: echo step 2 
       displayName: step 2

   - job: Job2
     displayName:  Second Job
     continueOnError: true
     workspace:
       clean: outputs
     steps:
     - script: echo step 1 
       displayName: step 1
     - script: echo step 2 
       displayName: step 2

- stage: B
  dependsOn: A
  condition: succeeded('A')
  jobs:
   - job: Job1
     displayName: Stage_2
     continueOnError: true
     workspace:
      clean: outputs
     steps:
     - script: echo step 1 
       displayName: step 1
     - script: echo step 2 
       displayName: step 2

   - job: Job2
     displayName:  Second Job
     continueOnError: true
     workspace:
       clean: outputs
     steps:
     - script: echo step 1 
       displayName: step 1
     - script: echo step 2 
       displayName: step 2
  
- stage: C
  dependsOn: A
  condition: no_succeeded('A')
  jobs:
   - job: Job1
     displayName: Stage_3
     continueOnError: true
     workspace:
      clean: outputs
     steps:
     - script: echo step 1 
       displayName: step 1
     - script: echo step 2 
       displayName: step 2

   - job: Job2
     displayName:  Second Job
     continueOnError: true
     workspace:
       clean: outputs
     steps:
     - script: echo step 1 
       displayName: step 1
     - script: echo step 2 
       displayName: step 2